#!/bin/bash
# -*- coding: utf-8 -*-
#
miscellaneous() {
    yad --title "Various Improvements" --height=90 --center --text "Add Various Configurations" --text-align=center \
        --button="Install Maintenance Tools":"xterm -e sudo pacman -S bleachbit timeshift crashplan --noconfirm" \
        --button="Install Variety":"xterm -e sudo pacman -S variety --noconfirm" \
        --button="Update pacman.conf":"xterm -e sudo mv /usr/share/pacman.conf /etc/" \
        --button="Back":1
}
        
install() {
    while :; do
    yad --title "Install" --height=80 --center --text "Install the Following, based on your Desktop Environment"  --text-align=center \
        --button="Install XFCE Updates":2 \
        --button="Install Mate Updates":3 \
        --button="Install LXQT Updates":4 \
        --button="Install Enlightenment Updates":5 \
        --button="Install i3 Updates":6 \
        --button="Back":1
    ret=$?

    case $ret in
        1) return ;;
        2) xfce ;;
        3) mate ;;
        4) lxqt ;;
        5) enlightenment ;;
        6) i3 ;;
    esac
done
}

xfce() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install XFCE-Cosmic":"xterm -e sudo pacman -S xfce-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}

mate() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install Mate-Cosmic":"xterm -e sudo pacman -S mate-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}

lxqt() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install LXQT-Cosmic":"xterm -e sudo pacman -S lxqt-cosmic-reborn --noconfirm" \
        --button="Back":1
}

enlightenment() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install Enlightenment-Cosmic":"xterm -e sudo pacman -S enlightenment-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}

i3() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install i3-Cosmic":"xterm -e sudo pacman -S i3-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}
while :; do
    action=$(yad --title "Reborn Improvements" --height=100 --width=300 --center --buttons-layout=center \
        --text="Arch Linux Made Easy" --text-align=center \
        --button="Miscellaneous":3 \
        --button="Close":1)

    ret=$?

    case $ret in
        1) exit 0 ;;
        3) miscellaneous ;;
    esac
done
