#!/bin/bash
# -*- coding: utf-8 -*-
#
miscellaneous() {
    yad --title "Various Improvements" --height=90 --center --text "Add Various Configurations" --text-align=center \
        --button="Make Sure BlueStar Repo Is Added":"xterm -e sudo mv /usr/share/pacman.conf /etc/" \
        --button="Install Skype":"xterm -e sudo pacman -S skype skype-call-recorder skypeforlinux-bin --noconfirm" \
        --button="Install Spotify":"xterm -e sudo pacman -S spotify spotify-adkiller blockify --noconfirm" \
        --button="Back":1
}
        
install() {
    while :; do
    yad --title "Install" --height=80 --center --text "Install the Following, based on your Desktop Environment"  --text-align=center \
        --button="Install Budgie Updates":2 \
        --button="Install Cinnamon Updates":3 \
        --button="Install KDE Updates":4 \
        --button="Install Openbox Updates":5 \
        --button="Back":1
    ret=$?

    case $ret in
        1) return ;;
        2) budgie ;;
        3) cinnamon ;;
        4) kde ;;
        5) openbox ;;
    esac
done
}

budgie() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install Budgie-Cosmic":"xterm -e sudo pacman -S budgie-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}

cinnamon() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install Cinnamon-Cosmic":"xterm -e sudo pacman -S cinnamon-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}

kde() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install KDE-Cosmic":"xterm -e sudo pacman -S kde-cosmic-reborn --noconfirm" \
        --button="Back":1
}

openbox() {
    yad --title "Install" --skip-taskbar --center --width=600 --text "Install the Following:" \
        --button="Install Openbox-Cosmic":"xterm -e sudo pacman -S openbox-cosmic-reborn --noconfirm" \
        --button="Install New Login Theme":"xterm -e sudo pacman -S lightdm-webkit-theme-aether --noconfirm" \
        --button="Configure Login Theme":"xterm -e sudo mv /usr/share/lightdm-webkit2-greeter.conf /etc/lightdm/" \
        --button="Back":1
}
while :; do
    action=$(yad --title "Reborn Improvements" --height=100 --width=300 --center --buttons-layout=center \
        --text="Arch Linux Made Easy" --text-align=center \
        --button="Install":2 \
        --button="Miscellaneous":3 \
        --button="Close":1)

    ret=$?

    case $ret in
        1) exit 0 ;;
        2) install ;;
        3) miscellaneous ;;
    esac
done
